# run chat-room docker container on kubernetes cluster (docker desktop) and expose service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-room
spec:
  selector:
    matchLabels:
      app: chat-room
  template:
    metadata:
      labels:
        app: chat-room
    spec:
      containers:
      - name: chat-room
        image: jongwon254/chat-room:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
