# Deployment of docker container on kubernetes cluster and exposing service as LoadBalancer
# Also runs on Azure Kubernetes Cluster

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-room
spec:
  selector:
    matchLabels:
      app: chat-room
  template:
    metadata:
      labels:
        app: chat-room
    spec:
      containers:
      - name: chat-room
        image: jongwon254/chat-room:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-room
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: chat-room
